---
# This playbook restarts the configured services

- name: Restart Apache
  action: service name=apache2 state=restarted
  tags: restart

- name: Restart MySQL
  action: service name=mysql state=restarted
  tags: restart

- name: Restart Memcache
  action: service name=memcached state=restarted
  tags: restart

- name: Restart Redis
  action: service name=redis-server state=restarted
  tags: restart