---
# This playbook installs node.js and related tools

- name: Node.js | Package prerequisites for node.js
  action: apt pkg={{ item }} state=installed
  tags: nodejs
  with_items:
    - software-properties-common
    - python-software-properties

- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
  tags: nodejs

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes
  tags: nodejs

- name: Node.js | Install nodejs and npm
  action: apt pkg={{ item }} state=installed
  tags: nodejs
  with_items:
    - nodejs

- name: Node.js | Install Express
  action: command npm install express
  tags: nodejs

